apps/recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.recipes, name='recetas'),
    path("crear/", views.create_recipe, name='create_recipe'),
    path("<slug:slug>/", views.recipe, name='recipe'),
    path("<slug:slug>/editar", views.edit_recipe, name='edit_recipe'),
    path("<slug:slug>/eliminar", views.delete_recipe, name='delete_recipe'),

    path('<int:i>/crear-ingredientes', views.create_recipe_ingredient_form, name='create_recipe_ingredient_form'),
    path('<int:i>/crear-pasos', views.create_recipe_step_form, name='create_recipe_step_form'),
    path('<int:i>/<slug:slug>/editar-ingredientes', views.edit_recipe_ingredient_form, name='edit_recipe_ingredient_form'),
    path('<int:i>/<slug:slug>/editar-pasos', views.edit_recipe_step_form, name='edit_recipe_step_form'),

    path('<int:i>/eliminar-ingrediente', views.delete_recipe_ingredient_form, name='delete_recipe_ingredient_form'),
    path('<int:i>/eliminar-paso', views.delete_recipe_step_form, name='delete_recipe_step_form'),
    path('<int:i>/<slug:slug>/eliminar-ingrediente-existente', views.delete_existing_recipe_ingredient_form, name='delete_existing_recipe_ingredient_form'),
    path('<int:i>/<slug:slug>/eliminar-paso-existente', views.delete_existing_recipe_step_form, name='delete_existing_recipe_step_form'),

    path('crear-categoria', views.create_category, name='create_category'),
    path('crear-etiqueta', views.create_tag, name='create_tag'),
    path('crear-ingrediente', views.create_ingredient, name='create_ingredient'),
]

ferias/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail import urls as wagtail_urls
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('website.urls'), name='sitio'),
    path('ferias/', include('marketplaces.urls'), name='ferias'),
    path('productos/', include('products.urls'), name='productos'),
    path('consejos/', include('content.urls'), name='consejos'),
    path('avisos/', include('feed.urls'), name='avisos'),
    # Redirect legacy blog route to Wagtail blog index
    path('blog/', RedirectView.as_view(url='/paginas/blog/', permanent=False), name='blog'),
    path('sugerencias/', include('crowdsourcing.urls'), name='sugerencias'),
    path('datos/', include('api.urls'), name='api'),
    path('usuarios/', include('users.urls'), name='usuarios'),
    path('recetas/', include('recipes.urls'), name='recetas'),
    path('cms/', include(wagtailadmin_urls)),     # Panel de administración de Wagtail
    path('documents/', include(wagtaildocs_urls)),  # Descarga de documentos
    path('paginas/', include(wagtail_urls)),  # Rutas públicas manejadas por Wagtail

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/recipes/models.py
from django.db import models
from django.utils.text import slugify
from products.models import Variety


class Allergy(models.Model):
    ALLERGY_CHOICES = {
        "gluten": "gluten",
        "dairy": "lácteos",
        "egg": "huevo",
        "nuts": "nueces",
        "soy": "soya",
        "fish": "pescado"
    }

    allergy = models.CharField(max_length=100, blank=True, choices=[(key, value) for key, value in ALLERGY_CHOICES.items()])

    def __str__(self):
        return self.allergy


class Ingredient(models.Model):
    """
    Data model: https://schema.org/recipeIngredient
    """

    ingredient_name = models.CharField(max_length=100, unique=True)
    ingredient_description = models.TextField(blank=True, null=True)
    # TODO: Evaluar cómo vincular con variedades de productos.
    ingredient_product = models.ForeignKey(Variety, blank=True, null=True, on_delete=models.SET_NULL)
    # Si no tenemos algún producto, puede quedar blank. Si sí está, vincular con el existente.
    allergies = models.ManyToManyField(Allergy, blank=True)
    
    def __str__(self):
        return self.ingredient_name


class Category(models.Model):
    """
    Recipe category. Examples: breakfast, lunch, dinner, dessert.
    Data model: https://schema.org/category
    """

    category_name = models.CharField(max_length=100, unique=True)
    category_description = models.TextField(blank=True, null=True)
    category_slug = models.SlugField(max_length=100, unique=True)

    def save(self, *args, **kwargs):
        if not self.category_slug:
            self.category_slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.category_name


class Tag(models.Model):
    """
    Keywords or tags for recipes. Examples: vegan, gluten-free, low-carb.
    Data model: https://schema.org/DefinedTerm
    """

    tag_name = models.CharField(max_length=50, unique=True)
    tag_slug = models.SlugField(max_length=50, unique=True)

    def save(self, *args, **kwargs):
        if not self.tag_slug:
            self.tag_slug = slugify(self.tag_name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.tag_name


class Recipe(models.Model):
    """
    Data model: https://schema.org/Recipe
    """

    name = models.CharField(max_length=512)
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    image = models.ImageField(upload_to="recipes/", blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    ingredients = models.ManyToManyField(Ingredient, through="RecipeIngredient")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, unique=True)

    cook_time = models.DurationField(null=True, blank=True)
    prep_time = models.DurationField(null=True, blank=True)
    total_time = models.DurationField(null=True, blank=True)
    recipe_yield = models.CharField(max_length=50, null=True, blank=True)
    recipe_cuisine = models.CharField(max_length=100, null=True, blank=True)

    storage = models.TextField(null=True, blank=True)
    origin = models.TextField(null=True, blank=True)
    references = models.TextField(null=True, blank=True)

    # Nutrition Information
    nutritional_value = models.TextField(null=True, blank=True)
    calories = models.CharField(max_length=20, null=True, blank=True)
    fat_content = models.CharField(max_length=20, null=True, blank=True)
    carbohydrate_content = models.CharField(max_length=20, null=True, blank=True)
    protein_content = models.CharField(max_length=20, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class RecipeIngredient(models.Model):
    """
    Data model: https://schema.org/recipeIngredient
    """

    UNIT_CHOICES = [
        ("g", "gramos"),
        ("kg", "kilogramos"),
        ("ml", "mililitros"),
        ("l", "litros"),
        ("tsp", "cucharadita"),
        ("tbsp", "cucharada"),
        ("cup", "taza"),
        ("unit", "unidad"),
        ("pinch", "pizca")
    ]

    UNIT_NAMES = {choice[0]: choice[1] for choice in UNIT_CHOICES}

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, null=True, blank=True, on_delete=models.SET_NULL)
    unit = models.CharField(max_length=50, choices=UNIT_CHOICES, default="unit")
    quantity = models.DecimalField(max_digits=8, decimal_places=3)

    class Meta:
        unique_together = ("recipe", "ingredient")

    def __str__(self):
        return f"{self.quantity} {self.UNIT_NAMES[self.unit]} of {self.ingredient.ingredient_name} for {self.recipe.name}"
    
    def get_unit_name(self):
        """Devuelve el nombre de la unidad en español."""
        return self.UNIT_NAMES.get(self.unit, self.unit)


class Step(models.Model):
    """
    Data model: https://schema.org/HowToStep
    """

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    step_sequence = models.IntegerField()
    title = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField()
    photo = models.ImageField(upload_to="steps/", blank=True, null=True)

    class Meta:
        ordering = ["step_sequence"]

    def __str__(self):
        return f"Step {self.step_sequence} for {self.recipe.name}: {self.description}"
    
    def to_dict(self):
        return {
            "@type": "HowToStep",
            "name": self.title if self.title else f"Step {self.step_sequence}",
            "text": self.description,
            "image": self.photo.url if self.photo else None,
            "position": self.step_sequence
        }
    

apps/recipes/templates/create_recipe.html
{% extends 'base.html' %}

{% load static %}

{% block page_title %} {{ title }} {% endblock %}

{% block bg-navbar %} background-amarillo {% endblock %}

{% block main %}

<!-- Hero -->
<div class="px-4 pt-3 pb-5 text-center background-amarillo">
    <div class="card col-lg-8 mx-auto bg-transparent border-0">
        <h1 class="display-3 my-5 text-white hero-deferia">{{texts.hero.content}}</h1>
        <h3 class="title-deferia text-white">¡Explorá nuestras recetas tradicionales,<br>desde el arroz con pollo hasta
            el gallo pinto!</h3>
        <img src="{% static 'images/stickers/ajo.svg' %}" width="75px" class="index-sticker-1">
        <img src="{% static 'images/stickers/acelga.svg' %}" width="75px" class="index-sticker-2">
        <img src="{% static 'images/stickers/naranja.svg' %}" width="75px" class="index-sticker-3">
    </div>
</div>

<!-- Formulario completo -->
<div class="container my-5">
    <h1 class="mb-4"><strong>{{ title }}</strong></h1>

    <form
        action="{% if recipe.slug %}{% url 'edit_recipe' recipe.slug %}{% else %}{% url 'create_recipe' %}{% endif %}"
        method="POST"
        enctype="multipart/form-data"
    > <!-- Si la receta tiene un slug, significa que la mandaron por context y debe usarse el form editar. Si no, es el form de crear receta. -->
    
        <div class="row mb-3">
            <div id="recipe-form" class="col mb-3">
                <div class="p-3 h-100 bg-white rounded">

                    <!-- Formulario de receta -->
                    {% csrf_token %}
                    {% include 'partials/recipe_form.html' with recipe_form=recipe_form %}

                    <!-- Formulario de ingredientes -->
                    <div class="row m-2">
                        <div class="p-3 bg-light rounded">
                            <div class="d-flex justify-content-between">
                                <h4>Ingredientes</h4>
                                <div>
                                    <button type="button" onclick="this.style.display='none'" class="btn-add-ingredient btn btn-sm btn-success" hx-get="{% if recipe.slug %}{% url 'edit_recipe_ingredient_form' next_ingredient recipe.slug %}{% else %}{% url 'create_recipe_ingredient_form' next_ingredient %}{% endif %}" hx-target="#ingredients-list" hx-swap="beforeend"><i class="fa fa-plus"></i></button>
                                </div>
                            </div>
                            
                            <div id="added-ingredients-list">
                                {% include 'partials/recipe_ingredient.html' with ingredient_formset=ingredient_formset %}
                            </div>
                            <div id="ingredients-list" class="mt-2">
                                {{ ingredient_formset.management_form }}
                            </div>
                        </div>
                    </div>

                    <!-- Formulario de pasos -->
                    <div class="row m-2">
                        <div class="p-3 bg-light rounded">
                            <div class="d-flex justify-content-between">
                                <h4>Pasos</h4>
                                <div>
                                    <button  type="button" onclick="this.style.display='none'" class="btn-add-step btn btn-sm btn-success" hx-get="{% if recipe.slug %}{% url 'edit_recipe_step_form' next_step recipe.slug %}{% else %}{% url 'create_recipe_step_form' next_step %}{% endif %}" hx-target="#steps-list" hx-swap="beforeend"><i class="fa fa-plus"></i></button>
                                </div>
                            </div>
                            
                            <div id="added-steps-list">
                                {% include 'partials/recipe_step.html' with step_formset=step_formset %}
                            </div>
                            <div id="steps-list" class="mt-2">
                                {{ step_formset.management_form }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 mb-3">
                <div class="p-3 background-verde rounded h-100">
                    <div class="mt-0">
                        <h4 class="text-light">Crear categoría</h4>
                        <div id="category-form" class="p-2 bg-white rounded">
                            {% include 'partials/new_category.html' with category_form=category_form %}
                        </div>
                    </div>

                    <div class="mt-3">
                        <h4 class="text-light">Crear etiqueta</h4>
                        <div id="tag-form" class="p-2 bg-white rounded">
                            {% include 'partials/new_tag.html' with tag_form=tag_form %}
                        </div>
                    </div>

                    <div class="mt-3">
                        <h4 class="text-light">Crear ingrediente</h4>
                        <div id="new-ingredient-form" class="p-2 bg-white rounded">
                            {% include 'partials/new_ingredient.html' with ingredient_form=ingredient_form %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-success w-100">Guardar receta</button>
            </div>
        </div>
    </form>
</div>

<script>
    document.getElementById('recipe-form').addEventListener('submit', function(event) {
        event.preventDefault();
        event.stopPropagation();

        updateFormsetManagement();

        event.target.submit();
    });

    document.getElementById('category-form').addEventListener('submit', function(event) {
        event.preventDefault();
        event.stopPropagation();
        event.target.submit();
    });

    document.getElementById('tag-form').addEventListener('submit', function(event) {
        event.preventDefault();
        event.stopPropagation();
        event.target.submit();
    });

    document.getElementById('new-ingredient-form').addEventListener('submit', function(event) {
        event.preventDefault();
        event.stopPropagation();
        event.target.submit();
    });

    function updateFormsetManagement() {
        saveItems('ingredients');
        saveItems('steps');
    }

    function saveItems(itemType) {
        const listName = itemType === 'ingredients' ? 'ingredients-list' : 'steps-list';
        const rowClass = itemType === 'ingredients' ? 'ingredient-row' : 'step-row';
        const totalFormsName = itemType === 'ingredients' ? 'ingredients-TOTAL_FORMS' : 'steps-TOTAL_FORMS';
        const initialFormsName = itemType === 'ingredients' ? 'ingredients-INITIAL_FORMS' : 'steps-INITIAL_FORMS';
        const minFormsName = itemType === 'ingredients' ? 'ingredients-MIN_NUM_FORMS' : 'steps-MIN_NUM_FORMS';

        const list = document.getElementById(listName);
        const itemElements = document.getElementsByClassName(rowClass);
        const totalItemCount = itemElements.length;

        const totalFormInputs = document.querySelectorAll(`[name$="${totalFormsName}"]`);
        totalFormInputs.forEach(input => input.value = totalItemCount);

        const initialFormInputs = document.querySelectorAll(`[name$="${initialFormsName}"]`);
        initialFormInputs.forEach(input => input.value = 0);

        const minFormInputs = document.querySelectorAll(`[name$="${minFormsName}"]`);
        minFormInputs.forEach(input => input.value = totalItemCount);
    }
</script>
    


{% endblock %}

apps/recipes/templates/recipe.html
{% extends 'base.html' %}

{% load static %}

{% load time_filters %}

{% block page_title %} {{ recipe.name|capfirst }} {% endblock %}

{% block bg-navbar %} background-amarillo {% endblock %}

{% block main %}

<!-- Hero -->
<div class="px-4 pt-3 pb-5 text-center background-amarillo">
    <div class="card col-lg-8 mx-auto bg-transparent border-0">
        <h1 class="display-3 my-5 text-white hero-deferia">Recetas de feria</h1>
        <img src="{% static 'images/stickers/ajo.svg' %}" width="75px" class="index-sticker-1">
        <img src="{% static 'images/stickers/acelga.svg' %}" width="75px" class="index-sticker-2">
        <img src="{% static 'images/stickers/naranja.svg' %}" width="75px" class="index-sticker-3">
    </div>
</div>

<!-- Una receta -->
<div class="card container mt-5 w-75 border-0 p-4">
    <div class="d-flex justify-content-between m-2">
        <div>
            <h1 class="mb-2"><strong>{{ recipe.name|capfirst }}</strong></h1>

            <!-- Etiquetas -->
            <div class="d-flex flex-wrap gap-2">
                {% for tag in recipe.tags.all %}
                <span class="badge rounded-pill background-verde">{{ tag.tag_name }}</span>
                {% endfor %}
            </div>
        </div>
        {% if user.is_staff %}
        <div class="d-flex justify-content-end pt-2">
            <a href="{% url 'edit_recipe' recipe.slug %}" class="link-warning text-black me-1"><i class="fa-solid fa-pen-to-square"></i></a>
            <a class="link-danger text-black ms-1" data-bs-toggle="modal" data-bs-target="#deleteModal{{ recipe.slug }}"><i class="fa fa-trash"></i></a>
        </div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col">
            <div class="align-items-start m-2">
                {% if recipe.image %}
                <img src="{{ recipe.image.url }}" class="img-fluid rounded" alt="{{ recipe.name }}">
                {% else %}
                <img src="{% static 'recipes/default_recipe_image.jpg' %}" class="img-fluid rounded"
                    alt="{{ recipe.name }}">
                {% endif %}
            </div>

            <!-- Ingredientes -->
            <div class="mt-4 m-2">
                <h3 class="mb-3 text-start"><strong>Ingredientes</strong></h3>
                <ul class="list-group">
                    {% for recipe_ingredient in recipe.recipeingredient_set.all %}
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        <div class="p-2 w-25 pill rounded background-verde p-2 text-white text-center m-1"><strong>{{ recipe_ingredient.quantity }}</strong></div>
                        <div class="p-2 w-25 pill rounded background-naranja p-2 text-white text-center m-1"><strong>{{ recipe_ingredient.get_unit_name }}</strong></div>
                        <div class="p-2"><strong>de</strong></div>
                        <div class="p-2 w-50 pill rounded background-amarillo p-2 text-center m-1"><strong>{{ recipe_ingredient.ingredient.ingredient_name }}</strong></div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            
        </div>
        <div class="col">
            <!-- Información de la receta -->
            <div class="m-2">
                {% if recipe.description %}
                <p class="mb-4">{{ recipe.description }}</p>
                {% endif %}

                {% if recipe.nutritional_value %}
                <p class="mb-4">{{ recipe.nutritional_value }}</p>
                {% endif %}

                {% if recipe.recipe_yield %}
                <div class="bg-white rounded p-2 border me-1 mb-2 w-100">
                    <p class="m-1"><i class="fa-solid fa-bowl-food"></i></p>
                    <p class="m-1"><strong>Porciones:</strong> {{ recipe.recipe_yield }}</p>
                </div>
                {% endif %}
                {% if recipe.recipe_cuisine %}
                <div class="bg-white rounded p-2 border ms-1 mb-2 w-100">
                    <p class="m-1"><i class="fa-solid fa-stroopwafel"></i></p>
                    <p class="m-1"><strong>Tipo de cocina:</strong> {{ recipe.recipe_cuisine }}</p>
                </div>
                {% endif %}
    
                <div class="bg-white rounded p-2 border">
                    <p class="m-1"><i class="fa-solid fa-clock"></i></p>
                    <p class="m-1"><strong>Preparación:</strong> {{ recipe.prep_time|format_timedelta }}</p>
                    <p class="m-1"><strong>Cocción:</strong> {{ recipe.cook_time|format_timedelta }}</p>
                    <p class="m-1"><strong>Total:</strong> {{ recipe.total_time|format_timedelta }}</p>
                </div>
            </div>

            <!-- Preparación -->
            <div class="mt-4 m-2">
                <h3 class="mb-3 text-start"><strong>Preparación</strong></h3>
                <ol class="list-group">
                    {% for step in recipe.step_set.all %}
                    <li class="list-group-item">
                        <h5>{{ step.step_sequence }}. {% if step.title %}{{ step.title }}{% endif %}</h5>
                        {{ step.description }}
                        {% if step.photo %}
                        <img src="{{ step.photo.url }}" class="img-fluid mt-2 rounded" alt="{{ step.title }}">
                        {% endif %}
                    </li>
                    {% endfor %}
                </ol>
            </div>

            {% if recipe.storage %}
            <div class="mt-4 m-2">
                <h3 class="mb-3 text-start"><strong>Forma de almacenamiento</strong></h3>
                <p class="mb-4">{{ recipe.storage }}</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% if user.is_staff %}
<div class="modal fade" id="deleteModal{{ recipe.slug }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ recipe.slug }}" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel{{ recipe.slug }}">Eliminar receta</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ¿Está seguro de que desea eliminar "{{ recipe.name }}"?
            </div>
            <div class="modal-footer">
                <a href="{% url 'delete_recipe' recipe.slug %}" class="btn btn-danger">Aceptar</a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

apps/recipes/templates/recipes.html
{% extends 'base.html' %}

{% load static %}

{% block page_title %} Todas las recetas {% endblock %}

{% block bg-navbar %} background-amarillo {% endblock %}

{% block main %}

<!-- Hero -->
<div class="px-4 pt-3 pb-5 text-center background-amarillo">
    <div class="card col-lg-8 mx-auto bg-transparent border-0">
        <h1 class="display-3 my-5 text-white hero-deferia">{{texts.hero.content}}</h1>
        <div class="card col-lg-6 mx-auto bg-transparent border-0">
            <h3 class="title-deferia text-white">{{ texts.hero_desc.content }}</h3>
        </div>
        <img src="{% static 'images/stickers/ajo.svg' %}" width="75px" class="index-sticker-1">
        <img src="{% static 'images/stickers/acelga.svg' %}" width="75px" class="index-sticker-2">
        <img src="{% static 'images/stickers/naranja.svg' %}" width="75px" class="index-sticker-3">
    </div>
</div>

<!-- Lista de las recetas -->
<div class="container my-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1><strong>Todas las recetas</strong></h1>
        <a href="{% url 'create_recipe' %}" class="btn btn-warning"><i class="fa-solid fa-plus me-2"></i><strong>Nueva receta</strong></a>
    </div>

    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
        {% for recipe in recipes %}
        <div class="col">
            <div class="card h-100 border-0 bg-white shadow-sm rounded">
                <div class="card-header border-0 bg-white" style="max-height: 1rem;">
                    <div class="d-flex flex-wrap gap-2" style="max-height: 1rem;">
                        {% for tag in recipe.tags.all %}
                        <span class="badge rounded-pill background-verde">{{ tag.tag_name }}</span>
                        {% endfor %}
                    </div>
                </div>
                <div class="card-body h-100">
                    {% if recipe.image %}
                    <img src="{{ recipe.image.url }}" class="card-img-bottom mt-2 mb-3 rounded w-100" alt="{{ recipe.name }}">
                    {% else %}
                    <img src="{% static 'recipes/default_recipe_image.jpg' %}" class="card-img-bottom mt-2 mb-3 rounded w-100" alt="{{ recipe.name }}">
                    {% endif %}

                    <h5 class="card-title">{{ recipe.name|capfirst }}</h5>
                    <p class="card-text">{{ recipe.description|truncatewords:15 }}</p>

                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'recipe' recipe.slug %}" class="btn btn-sm btn-danger"><strong><i class="fa-solid fa-chevron-down me-2"></i>Ver receta</strong></a>
                        
                        {% if user.is_staff %}
                        <div class="d-flex justify-content-end pt-2">
                            <a href="{% url 'edit_recipe' recipe.slug %}" class="link-warning text-dark me-1"><i class="fa-solid fa-pen-to-square"></i></a>
                            <a class="link-danger text-dark ms-1" data-bs-toggle="modal" data-bs-target="#deleteModal{{ recipe.slug }}"><i class="fa fa-trash"></i></a>
                        </div>
                        
                        <div class="modal fade" id="deleteModal{{ recipe.slug }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ recipe.slug }}" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="deleteModalLabel{{ recipe.slug }}">Eliminar receta</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        ¿Está seguro de que desea eliminar "{{ recipe.name }}"?
                                    </div>
                                    <div class="modal-footer">
                                        <a href="{% url 'delete_recipe' recipe.slug %}" class="btn btn-danger">Aceptar</a>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
                <div class="card-footer h-100 border-0 bg-white"></div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}